server:
  port: 9001
spring:
  application:
    name: gateway
  jmx:
    enabled: false
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: zt-nlp-workflow
        uri: lb://ZT-NLP-WORKFLOW
        predicates:
        - Path=/workflow/**
      - id: workflow_route
        uri: http://www.163.com/
        predicates:
        - Path=/163
  zipkin:
    base-url: http://192.168.230.1:9987/
  #这里把抽样百分比设置为1，即信息全部采集
  sleuth:
    sampler:
      probability: 1.0
eureka:
  instance:
    prefer-ip-address: true 
  client:
    register-with-eureka: true 
    fetch-registry: true 
    service-url:
      defaultZone: http://easysass:easysass123@localhost:8761/eureka #Eureka服务位置
filters:
# 熔断降级配置
- name: Hystrix
  args:
    name : default
    fallbackUri: 'forward:/defaultfallback'
# hystrix 信号量隔离，3秒后自动超时
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 3000
  shareSecurityContext: true