server:
  port: 8761

eureka:
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 4000
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://easysass:easysass123@localhost:${server.port}/eureka/
# 安全认证的配置  
spring:
  security:
    basic:
      enabled: true
    user: 
      name: easysass
      password: easysass123
#spring.cloud.config.discovery.enabled: true