server:
  port: 8090
  servlet:
    session:
      timeout: 604800 # session有效期7天
spring:
  application:
    name: xinyue-server-a
eureka:
  instance:
    prefer-ip-address: true 
  client:
    register-with-eureka: true 
    fetch-registry: true 
    service-url:
      defaultZone: http://easysass:easysass123@localhost:8761/eureka #Eureka服务位置

      